### PR TITLE
Update for version 1.0+ of cc test reporter

### PR DESCRIPTION
**Pull request by jrafanie**
https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03

### CODE REVIEW

**Comment by jrafanie** [comment]
@bdunne please review

**Comment by jrafanie** [comment]
Closing as it's included in #7

**Comment by bdunne** [comment]
@jrafanie Did you intend to close this?

**Comment by jrafanie** [comment]
@bdunne wasn't it included in #7 ?

**Comment by bdunne** [comment]
Yes it is, closing...

**Pull request closed without merging**
